# Generated by Django 6.1 on 2026-08-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('refused_plate', 'Plaque refusée'), ('unknown_face', 'Visage inconnu'), ('spoof_attempt', "Tentative d'usurpation")], max_length=32),
        ),
    ]
