# Generated by Django 6.1 on 2026-08-31 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alert_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('check_in', 'Arrivée (Check-in)'), ('departure_update', 'Mise à jour départ (Check-out)'), ('passage', 'Passage')], default='check_in', max_length=32)),
                ('camera_id', models.CharField(blank=True, max_length=64)),
                ('confidence', models.FloatField(default=0.0)),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='attendance_audits/')),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.attendance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date', '-heure', '-id'),
            },
        ),
    ]
