# Generated by Django 6.1 on 2026-08-31 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendanceaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslog',
            name='audit_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attendance',
            name='audit_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='attendanceaudit',
            name='audit_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='alert',
            name='kind',
            field=models.CharField(choices=[('refused_plate', 'Plaque refusée'), ('unknown_face', 'Visage inconnu'), ('spoof_attempt', "Tentative d'usurpation"), ('signal_loss', 'Perte de signal caméra'), ('tamper_attempt', 'Sabotage / Obstruction caméra')], max_length=32),
        ),
    ]
