# Generated by Django 6.1 on 2026-08-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_accesslog_audit_hash_attendance_audit_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=512)),
                ('task', models.CharField(choices=[('attendance', 'Pointage Facial'), ('anpr', 'Portail & Véhicules (ANPR)')], default='attendance', max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, max_length=128)),
                ('resolution', models.CharField(default='1080p', max_length=32)),
                ('fps', models.IntegerField(default=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
